version: "3.8"
services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: webprog_project
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db/
volumes:
  mongodata:
    driver: local
